name: Run Playwright & Cucumber Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Instalar dependências
        run: npm install

      - name: Instalar Playwright Browsers
        run: npx playwright install --with-deps

      - name: Executar testes Playwright
        run: npm run test:report

      - name: Executar testes Cucumber
        run: npm run cucumber-report

      - name: Gerar relatório Cucumber HTML
        run: npm run generate-report

      - name: Salvar relatório Playwright
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Salvar relatório Cucumber
        uses: actions/upload-artifact@v4
        with:
          name: cucumber-report
          path: reports/cucumber-report.html
          retention-days: 7

      - name: Salvar artefatos em caso de falha
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/
